**How to Use CEL Atomic Data**

The atomic data for *collisionally excited lines (CEL)* contain Energy Levels (Ej), Collision Strengths (Ωij), and Transition Probabilities (Aij). We have four atomic datasets for them: collection, chianti52, chianti60, and chianti70.

You need to load the atomneb library as follows:

In [1]:
import atomneb
import numpy as np
import os

base_dir = '.'
data_dir = os.path.join('atomic-data', 'chianti70')

atom_elj_file = os.path.join(base_dir,data_dir, 'AtomElj.fits')
atom_omij_file = os.path.join(base_dir,data_dir, 'AtomOmij.fits')
atom_aij_file = os.path.join(base_dir,data_dir, 'AtomAij.fits')
elj_data_list = atomneb.read_elj_list(atom_elj_file)
omij_data_list = atomneb.read_omij_list(atom_omij_file)
aij_data_list = atomneb.read_aij_list(atom_aij_file)

Now you have access to the following information:

* *Energy Levels* (Ej):

In [2]:
atom='o'
ion='iii'
oiii_elj_data = atomneb.read_elj(atom_elj_file, atom, ion, level_num=6)
print(oiii_elj_data['j_v'])
print(oiii_elj_data['ej'])

[0. 1. 2. 2. 0. 2.]
[    0.           113.19999695   306.20001221 20273.30078125
 43185.69921875 60324.80078125]


* *Collision Strengths* (Ωij):

In [3]:
atom='o'
ion='iii'
oiii_omij_data = atomneb.read_omij(atom_omij_file, atom, ion)
print(oiii_omij_data['level1'])
print(oiii_omij_data['level2'])
print(oiii_omij_data['strength'][0])

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2
  2  2  2  2  3  3  3  3  3  3  3  3  3  3  3  3  4  4  4  4  4  4  4  4
  4  4  4  5  5  5  5  5  5  5  5  5  6  6  6  6  6  6  6  7  7  7  7  7
  8  8  8  8  8  8  8  9  9  9 10 10 10 10 10 11 13 13 14]
[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15  3  4  5  6  7  8  9 10 11
 12 13 14 15  4  5  6  7  8  9 10 11 12 13 14 15  5  6  7  8  9 10 11 12
 13 14 15  7  8  9 10 11 12 13 14 15  7  8  9 10 11 12 14  8  9 10 11 12
  9 10 11 12 13 14 15 10 11 12 11 12 13 14 15 12 14 15 15]
[1.0000000e+02 1.5850000e+02 2.5120000e+02 3.9810000e+02 6.3100000e+02
 1.0000000e+03 1.5849000e+03 2.5119000e+03 3.9811000e+03 6.3096000e+03
 1.0000000e+04 1.5848900e+04 2.5118900e+04 3.9810700e+04 6.3095800e+04
 1.0000000e+05 1.5848920e+05 2.5118870e+05 3.9810710e+05 6.3095760e+05
 1.0000000e+06 1.5848925e+06 2.5118870e+06]


* *Transition Probabilities* (Aij):

In [4]:
atom='o'
ion='iii'
oiii_aij_data = atomneb.read_aij(atom_aij_file, atom, ion)
print(oiii_aij_data['aij'][0])

[[0.00000000e+00 2.59699991e-05 0.00000000e+00 2.32200000e-06
  0.00000000e+00 0.00000000e+00 0.00000000e+00 4.12000000e+08
  0.00000000e+00 0.00000000e+00 7.94000000e+08 0.00000000e+00
  0.00000000e+00 1.94000000e+09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.63200000e-05 6.79099979e-03
  2.25500003e-01 1.45000000e+02 5.54000000e+08 2.99000000e+08
  0.00000000e+00 2.40000000e+09 6.12000000e+08 5.86000000e+08
  0.00000000e+00 5.83000013e+09 1.23000000e+06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.04600003e-02
  6.99799974e-04 4.26000000e+02 1.73000000e+08 1.87000000e+07
  7.24000000e+08 0.00000000e+00 9.91000000e+08 1.80000000e+09
  3.13000000e+05 9.72999987e+09 3.71000000e+05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.68499994e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.95000000e+04 0.00000000e+00 3.09000000e+04 0.00000000e+00
  7.36999987e+09 7.01000000e+05 1.26000005e+10]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  

**How to Use RL Atomic Data**

The atomic data for *recombination lines (RC)* contain effective recombination coefficients (αeff) of emission lines from different collections: RC Collection, SH95 Collection, PPB91 Collection, PFSD12 He I data, FSL13 N II data, and SSB17 O II data.

You need to load the atomneb libary:

In [5]:
import atomneb
import numpy as np
import os

base_dir = '.'
data_rc_dir = os.path.join('atomic-data-rc')

Now you have access to effective recombination coefficients (αeff) of the following information:

* *RC Collection*:

In [6]:
atom_rc_file = os.path.join(base_dir,data_rc_dir, 'rc_collection.fits')
atom='c'
ion='iii'
cii_rc_data = atomneb.read_aeff_collection(atom_rc_file, atom, ion)
n_line = len(cii_rc_data['wavelength'])
for i in range(0, n_line):
     print(cii_rc_data['wavelength'][i], cii_rc_data['a'][i],
           cii_rc_data['b'][i], cii_rc_data['c'][i],
           cii_rc_data['d'][i], cii_rc_data['f'][i])

914.0 0.6928 0.0214 -0.0163 -0.2431 -0.88
962.0 1.0998 -0.0042 -0.0279 -0.2294 -0.9656
997.0 0.7821 -0.3684 0.0003 -0.1217 -0.7874
1064.0 1.7852 -0.0545 -0.0387 -0.2083 -1.1416
1066.0 4.873 -0.1628 0.0218 -0.1224 -0.6327
1142.0 7.0215 -0.2315 -0.0418 -0.1438 -0.7814
1157.0 0.3719 -0.2897 -0.0547 -0.1232 -0.7311
1232.0 2.4954 -0.4875 0.0411 -0.1048 -0.8786
1270.0 0.6192 -0.3684 0.0003 -0.1217 -0.7874
1324.0 1.0791 -2.2342 1.3884 -0.0351 -1.8815
1505.0 0.4713 -0.2897 -0.0547 -0.1232 -0.731
1548.0 0.5822 -0.3683 0.0003 -0.1217 -0.7874
1632.0 0.3392 0.1347 0.1315 -0.3513 -0.5759
1653.0 0.4268 0.0756 0.0805 -0.3075 -0.6214
1682.0 0.4819 0.0098 0.0357 -0.2643 -0.6689
1721.0 0.9989 -0.1628 0.0218 -0.1224 -0.6327
1760.0 1.8751 -2.4378 1.8571 -0.4779 -2.8843
1762.0 38.774 -0.7516 0.1397 -0.281 -1.4218
1796.0 2.1427 -0.0835 -0.0477 -0.1866 -0.7186
1910.0 3.3153 -0.083 -0.0577 -0.1883 -0.7634
1930.0 0.5205 -0.2315 -0.0418 -0.1438 -0.7815
2138.0 6.2474 -0.0858 -0.0558 -0.1889 -0.7936
2140.0 0.3753

* *SH95 Collection*:

In [7]:
atom_rc_file = os.path.join(base_dir,data_rc_dir, 'rc_SH95.fits')
atom='h'
ion='ii'
hi_rc_data = atomneb.read_aeff_sh95(atom_rc_file, atom, ion)
print(hi_rc_data['aeff'][0])

[[1.000e+02 5.000e+02 0.000e+00 ... 0.000e+00 4.542e-24 3.293e-23]
 [1.000e+03 5.000e+02 0.000e+00 ... 0.000e+00 4.612e-24 3.795e-23]
 [1.000e+04 5.000e+02 0.000e+00 ... 0.000e+00 4.758e-24 4.365e-23]
 ...
 [1.000e+12 3.000e+04 0.000e+00 ... 0.000e+00 1.372e-25 1.801e-24]
 [1.000e+13 3.000e+04 0.000e+00 ... 0.000e+00 1.488e-25 1.937e-24]
 [1.000e+14 3.000e+04 0.000e+00 ... 0.000e+00 1.599e-25 2.408e-24]]


* *PPB91 Collection*:

In [8]:
atom_rc_file = os.path.join(base_dir,data_rc_dir, 'rc_PPB91.fits')
atom='c'
ion='iii'
cii_rc_data = atomneb.read_aeff_ppb91(atom_rc_file, atom, ion)
n_line = len(cii_rc_data['wavelength'])
for i in range(0, n_line):
   print(cii_rc_data['ion'][i], cii_rc_data['case1'][i], cii_rc_data['wavelength'][i],
         cii_rc_data['a'][i], cii_rc_data['b'][i], cii_rc_data['c'][i],
         cii_rc_data['d'][i], cii_rc_data['br'][i], cii_rc_data['q'][i], cii_rc_data['y'][i])

C2+ A 9903.46 0.697 -0.784 4.205 0.72 1.0 A 1.621
C2+ A 4267.15 1.011 -0.754 2.587 0.719 0.95 A 2.795
C2+ A 7236.42 1.724 -0.7 1.683 0.667 0.012 C 0.065
C2+ B 7236.42 1.724 -0.7 1.683 0.667 0.95 C 5.184
C2+ A 6582.88 0.584 -0.521 0.624 0.681 0.17 C 0.329
C2+ B 6582.88 2.334 -0.649 0.768 0.564 0.17 C 1.444
C2+ A 2837.0 0.584 -0.521 0.624 0.681 0.313 C 0.606
C2+ B 2837.0 2.334 -0.649 0.768 0.564 0.313 C 2.658
C2+ A 1761.0 0.584 -0.521 0.624 0.681 0.517 C 1.001
C2+ B 1761.0 2.334 -0.649 0.768 0.564 0.517 C 4.391
C2+ A 1335.0 0.953 -0.539 0.412 0.654 1.0 C 3.45
C2+ B 1335.0 1.993 -0.63 0.624 0.681 1.0 C 7.682


* *PFSD12 He I data*:

In [9]:
atom_rc_file = os.path.join(base_dir,data_rc_dir, 'rc_he_ii_PFSD12.fits')
atom='he'
ion='ii'
hei_rc_data = atomneb.read_aeff_he_i_pfsd12(atom_rc_file, atom, ion)
hei_rc_data_wave = atomneb.read_aeff_he_i_pfsd12(atom_rc_file, atom, ion, wavelength=True)
print(hei_rc_data['aeff'][0])

[[ 5.000000e+03  1.000000e+01 -2.537954e+01 ... -2.723860e+01
  -2.677585e+01 -2.725261e+01]
 [ 6.000000e+03  1.000000e+01 -2.542802e+01 ... -2.728124e+01
  -2.685544e+01 -2.733224e+01]
 [ 7.000000e+03  1.000000e+01 -2.546983e+01 ... -2.731739e+01
  -2.692480e+01 -2.740163e+01]
 ...
 [ 2.300000e+04  1.000000e+14 -2.611640e+01 ... -2.769109e+01
  -2.731302e+01 -2.779088e+01]
 [ 2.400000e+04  1.000000e+14 -2.614921e+01 ... -2.772712e+01
  -2.734328e+01 -2.782114e+01]
 [ 2.500000e+04  1.000000e+14 -2.618047e+01 ... -2.776133e+01
  -2.737219e+01 -2.785005e+01]]


* *FSL13 N II data*:

In [10]:
atom_rc_file = os.path.join(base_dir,data_rc_dir, 'rc_n_iii_FSL13.fits')
atom='n'
ion='iii'
wavelength_range=[4400.0, 7100.0]
nii_rc_data = atomneb.read_aeff_n_ii_fsl13(atom_rc_file, atom, ion, wavelength_range)
nii_rc_data_wave = atomneb.read_aeff_n_ii_fsl13(atom_rc_file, atom, ion, wavelength_range, wavelength=True)
print(nii_rc_data['aeff'][0])
n_line = len(hei_rc_data_wave['wavelength'])
for i in range(0, n_line):
   print(nii_rc_data_wave['wavelength'][i], nii_rc_data_wave['tr'][i], nii_rc_data_wave['trans'][i])

[[255.          79.5         47.29999924  12.5          6.19999981
    4.           2.8599999 ]
 [258.          54.40000153  29.70000076   7.92000008   4.11000013
    2.72000003   2.        ]
 [310.          48.09999847  23.70000076   5.19000006   2.54999995
    1.64999998   1.21000004]
 [434.          50.29999924  23.20000076   4.71000004   2.25999999
    1.45000005   1.04999995]]
6413.22998046875 6g - 4f 2p6g G[9/2]o4 - 2p4f F[7/2]e3
6556.31982421875 6g - 4f 2p6g G[9/2]o5 - 2p4f G[7/2]e4
6456.97021484375 6g - 4f 2p6g G[9/2]o5 - 2p4f F[7/2]e4
6446.52978515625 6g - 4f 2p6g F[7/2]o3 - 2p4f D[5/2]e2
6445.33984375 6g - 4f 2p6g F[7/2]o4 - 2p4f D[5/2]e3
4694.64013671875 4f - 3d 1Po 2p4f D[5/2]e2 - 2p3d(1Po 1)
4442.009765625 4f - 3d 3Po 2p4f D[5/2]e2 - 2p3d(3Po 1)
4432.740234375 4f - 3d 3Po 2p4f D[5/2]e3 - 2p3d(3Po 2)
4530.41015625 4f - 3d 1Fo 2p4f G[9/2]e4 - 2p3d(1Fo 3)
4552.52001953125 4f - 3d 1Fo 2p4f G[7/2]e4 - 2p3d(1Fo 3)
6809.97998046875 4p 3Se - 3d 3Po 2p4p(3Se 1) - 2p3d(3Po 2)
6167.7

* *SSB17 O II data*: You first need to unpack rc_o_iii_SSB17_orl_case_b.fits.tar.gz:

In [11]:
import atomneb
import numpy as np
import os
import tarfile

base_dir = '.'
data_rc_dir = os.path.join('atomic-data-rc')
atom_rc_file = os.path.join(base_dir,data_rc_dir, 'rc_o_iii_SSB17_orl_case_b.fits')

atom_rc_file_tar_gz = os.path.join(base_dir,data_rc_dir, 'rc_o_iii_SSB17_orl_case_b.fits.tar.gz')
atom_rc_path = os.path.join(base_dir,data_rc_dir)
tar = tarfile.open(atom_rc_file_tar_gz, "r:gz")
tar.extractall(path=atom_rc_path)
tar.close()

If you need to have access to the full dataset (entire wavelengths, case A and B), unpack rc_o_iii_SSB17.fits.tar.gz. Please note that using the entire atomic data will make your program very slow and you may need to have a higher memory on your system. Without the above comment, as default, the cose uses rc_o_iii_SSB17_orl_case_b.fits:

In [12]:
import atomneb
import numpy as np
import os

base_dir = '.'
data_rc_dir = os.path.join('atomic-data-rc')
atom_rc_file = os.path.join(base_dir,data_rc_dir, 'rc_o_iii_SSB17_orl_case_b.fits')

atom = 'o'
ion = 'iii' # O II
case1 = 'B'
wavelength_range=[5320.0, 5330.0]
oii_rc_data = atomneb.read_aeff_o_ii_ssb17(atom_rc_file, atom, ion, case1, wavelength_range)
oii_rc_data_wave = atomneb.read_aeff_o_ii_ssb17(atom_rc_file, atom, ion, case1, wavelength_range, wavelength=True)
print(oii_rc_data['aeff'][0])
n_line = len(oii_rc_data_wave['wavelength'])
for i in range(0, n_line):
   print(oii_rc_data_wave['wavelength'][i], oii_rc_data_wave['lower_term'][i], oii_rc_data_wave['upper_term'][i])

[[1.641e-30 1.600e-30 1.564e-30 1.541e-30 1.521e-30 1.509e-30 1.504e-30
  1.505e-30 1.509e-30 1.518e-30 1.530e-30 1.545e-30 1.548e-30 1.565e-30
  1.584e-30 1.612e-30]
 [1.302e-30 1.263e-30 1.224e-30 1.192e-30 1.171e-30 1.154e-30 1.144e-30
  1.139e-30 1.138e-30 1.141e-30 1.148e-30 1.157e-30 1.158e-30 1.169e-30
  1.183e-30 1.187e-30]
 [1.033e-30 9.958e-31 9.586e-31 9.261e-31 8.999e-31 8.835e-31 8.702e-31
  8.621e-31 8.582e-31 8.579e-31 8.608e-31 8.593e-31 8.659e-31 8.738e-31
  8.830e-31 8.854e-31]
 [8.080e-31 7.746e-31 7.440e-31 7.144e-31 6.892e-31 6.693e-31 6.546e-31
  6.475e-31 6.418e-31 6.362e-31 6.359e-31 6.380e-31 6.419e-31 6.470e-31
  6.533e-31 6.546e-31]
 [6.379e-31 6.116e-31 5.864e-31 5.609e-31 5.383e-31 5.196e-31 5.052e-31
  4.949e-31 4.884e-31 4.847e-31 4.834e-31 4.841e-31 4.864e-31 4.897e-31
  4.899e-31 4.948e-31]
 [5.023e-31 4.842e-31 4.637e-31 4.443e-31 4.249e-31 4.082e-31 3.947e-31
  3.848e-31 3.782e-31 3.741e-31 3.722e-31 3.721e-31 3.733e-31 3.754e-31
  3.753e-31 3.788e-31